<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="SipLib">
      <HintPath>..\..\..\ClassLibrary\bin\Debug\net9.0\SipLib.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="testv\dtx.inp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\test_dec.bat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\test_enc.bat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst.inp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst_m0.cod">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst_m0.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst_m1.cod">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst_m1.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst_m2.cod">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst_m2.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst_m3.cod">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst_m3.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst_m4.cod">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst_m4.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst_m5.cod">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst_m5.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst_m6.cod">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst_m6.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst_m7.cod">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst_m7.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst_m8.cod">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst_m8.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst_md.cod">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="testv\tst_md.out">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
